services:
  db:
    image: postgres:16-alpine
    container_name: game_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - game-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - game-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/game?sslmode=disable
<<<<<<< HEAD
      JWT_SECRET: my_secret_key
=======
      JWT_SECRET: ${JWT_SECRET}
>>>>>>> date-+++
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-noreply@seabattle.ru}
    depends_on:
      - db
    networks:
      - game-network

  frontend:
    build:
      context: ../Sea-Battle-Frontend-GUI
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    container_name: game_frontend
    restart: always
    ports:
<<<<<<< HEAD
      - "5173:5173"
=======
      - "5173:80"
>>>>>>> date-+++
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

volumes:
  db_data: