apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: sea-battle
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@postgres:5432/game?sslmode=disable"
  JWT_SECRET: "my_secret_key"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_USERNAME: "SeaBattle30@gmail.com"
  SMTP_PASSWORD: "tfkw heia fheq bnhq"
  SMTP_FROM: "SeaBattle30@gmail.com"
