// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :exec
INSERT INTO games (id, player1_id, status, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateGameParams struct {
	ID        uuid.UUID
	Player1ID uuid.UUID
	Status    string
	CreatedAt time.Time
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) error {
	_, err := q.db.ExecContext(ctx, createGame,
		arg.ID,
		arg.Player1ID,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, player1_id, player2_id, status, current_turn, winner_id, finished_at, created_at
FROM games WHERE id = $1
`

type GetGameRow struct {
	ID          uuid.UUID
	Player1ID   uuid.UUID
	Player2ID   uuid.NullUUID
	Status      string
	CurrentTurn uuid.NullUUID
	WinnerID    uuid.NullUUID
	FinishedAt  *time.Time
	CreatedAt   time.Time
}

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (GetGameRow, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Status,
		&i.CurrentTurn,
		&i.WinnerID,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveGames = `-- name: GetActiveGames :many
SELECT id, player1_id, player2_id, status, current_turn, winner_id, finished_at, created_at
FROM games WHERE status IN ('waiting', 'placing_ships', 'playing')
`

func (q *Queries) GetActiveGames(ctx context.Context) ([]GetGameRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameRow
	for rows.Next() {
		var i GetGameRow
		if err := rows.Scan(
			&i.ID,
			&i.Player1ID,
			&i.Player2ID,
			&i.Status,
			&i.CurrentTurn,
			&i.WinnerID,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerActiveGames = `-- name: GetPlayerActiveGames :many
SELECT id, player1_id, player2_id, status, current_turn, winner_id, finished_at, created_at
FROM games
WHERE (player1_id = $1 OR player2_id = $1)
  AND status IN ('waiting', 'placing_ships', 'playing')
`

func (q *Queries) GetPlayerActiveGames(ctx context.Context, playerID uuid.UUID) ([]GetGameRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerActiveGames, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameRow
	for rows.Next() {
		var i GetGameRow
		if err := rows.Scan(
			&i.ID,
			&i.Player1ID,
			&i.Player2ID,
			&i.Status,
			&i.CurrentTurn,
			&i.WinnerID,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGamePlayer2 = `-- name: UpdateGamePlayer2 :exec
UPDATE games SET player2_id = $2, status = 'placing_ships' WHERE id = $1
`

type UpdateGamePlayer2Params struct {
	ID        uuid.UUID
	Player2ID uuid.NullUUID
}

func (q *Queries) UpdateGamePlayer2(ctx context.Context, arg UpdateGamePlayer2Params) error {
	_, err := q.db.ExecContext(ctx, updateGamePlayer2, arg.ID, arg.Player2ID)
	return err
}

const updateGameStatus = `-- name: UpdateGameStatus :exec
UPDATE games SET status = $2, current_turn = $3, winner_id = $4, finished_at = $5 WHERE id = $1
`

type UpdateGameStatusParams struct {
	ID          uuid.UUID
	Status      string
	CurrentTurn uuid.NullUUID
	WinnerID    uuid.NullUUID
	FinishedAt  *time.Time
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGameStatus,
		arg.ID,
		arg.Status,
		arg.CurrentTurn,
		arg.WinnerID,
		arg.FinishedAt,
	)
	return err
}

const saveGameShip = `-- name: SaveGameShip :exec
INSERT INTO game_ships (id, game_id, player_id, ship_type, start_x, start_y, horizontal)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveGameShipParams struct {
	ID         uuid.UUID
	GameID     uuid.UUID
	PlayerID   uuid.UUID
	ShipType   int32
	StartX     int32
	StartY     int32
	Horizontal bool
}

func (q *Queries) SaveGameShip(ctx context.Context, arg SaveGameShipParams) error {
	_, err := q.db.ExecContext(ctx, saveGameShip,
		arg.ID,
		arg.GameID,
		arg.PlayerID,
		arg.ShipType,
		arg.StartX,
		arg.StartY,
		arg.Horizontal,
	)
	return err
}

const getGameShips = `-- name: GetGameShips :many
SELECT id, game_id, player_id, ship_type, start_x, start_y, horizontal
FROM game_ships WHERE game_id = $1
`

type GetGameShipsRow struct {
	ID         uuid.UUID
	GameID     uuid.UUID
	PlayerID   uuid.UUID
	ShipType   int32
	StartX     int32
	StartY     int32
	Horizontal bool
}

func (q *Queries) GetGameShips(ctx context.Context, gameID uuid.UUID) ([]GetGameShipsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGameShips, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameShipsRow
	for rows.Next() {
		var i GetGameShipsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.ShipType,
			&i.StartX,
			&i.StartY,
			&i.Horizontal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerGameShips = `-- name: GetPlayerGameShips :many
SELECT id, game_id, player_id, ship_type, start_x, start_y, horizontal
FROM game_ships WHERE game_id = $1 AND player_id = $2
`

type GetPlayerGameShipsParams struct {
	GameID   uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) GetPlayerGameShips(ctx context.Context, arg GetPlayerGameShipsParams) ([]GetGameShipsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerGameShips, arg.GameID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameShipsRow
	for rows.Next() {
		var i GetGameShipsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.ShipType,
			&i.StartX,
			&i.StartY,
			&i.Horizontal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteGameShips = `-- name: DeleteGameShips :exec
DELETE FROM game_ships WHERE game_id = $1
`

func (q *Queries) DeleteGameShips(ctx context.Context, gameID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGameShips, gameID)
	return err
}

const deletePlayerGameShips = `-- name: DeletePlayerGameShips :exec
DELETE FROM game_ships WHERE game_id = $1 AND player_id = $2
`

type DeletePlayerGameShipsParams struct {
	GameID   uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) DeletePlayerGameShips(ctx context.Context, arg DeletePlayerGameShipsParams) error {
	_, err := q.db.ExecContext(ctx, deletePlayerGameShips, arg.GameID, arg.PlayerID)
	return err
}

const saveGameMove = `-- name: SaveGameMove :exec
INSERT INTO game_moves (id, game_id, player_id, x, y, hit, sunk_ship_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveGameMoveParams struct {
	ID        uuid.UUID
	GameID    uuid.UUID
	PlayerID  uuid.UUID
	X         int32
	Y         int32
	Hit       bool
	SunkShipID uuid.NullUUID
}

func (q *Queries) SaveGameMove(ctx context.Context, arg SaveGameMoveParams) error {
	_, err := q.db.ExecContext(ctx, saveGameMove,
		arg.ID,
		arg.GameID,
		arg.PlayerID,
		arg.X,
		arg.Y,
		arg.Hit,
		arg.SunkShipID,
	)
	return err
}

const getGameMoves = `-- name: GetGameMoves :many
SELECT id, game_id, player_id, x, y, hit, sunk_ship_id
FROM game_moves WHERE game_id = $1
`

type GetGameMovesRow struct {
	ID        uuid.UUID
	GameID    uuid.UUID
	PlayerID  uuid.UUID
	X         int32
	Y         int32
	Hit       bool
	SunkShipID uuid.NullUUID
}

func (q *Queries) GetGameMoves(ctx context.Context, gameID uuid.UUID) ([]GetGameMovesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGameMoves, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameMovesRow
	for rows.Next() {
		var i GetGameMovesRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.X,
			&i.Y,
			&i.Hit,
			&i.SunkShipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
