// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobbies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addLobbyPlayer = `-- name: AddLobbyPlayer :exec
INSERT INTO lobby_players (lobby_id, player_id) VALUES ($1, $2)
`

type AddLobbyPlayerParams struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) AddLobbyPlayer(ctx context.Context, arg AddLobbyPlayerParams) error {
	_, err := q.db.ExecContext(ctx, addLobbyPlayer, arg.LobbyID, arg.PlayerID)
	return err
}

const createLobby = `-- name: CreateLobby :one
INSERT INTO lobbies (id, creator_id, invite_code, max_players)
VALUES ($1, $2, $3, $4)
RETURNING id, creator_id, status, invite_code, max_players, created_at
`

type CreateLobbyParams struct {
	ID         uuid.UUID
	CreatorID  uuid.UUID
	InviteCode string
	MaxPlayers int32
}

func (q *Queries) CreateLobby(ctx context.Context, arg CreateLobbyParams) (Lobby, error) {
	row := q.db.QueryRowContext(ctx, createLobby,
		arg.ID,
		arg.CreatorID,
		arg.InviteCode,
		arg.MaxPlayers,
	)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Status,
		&i.InviteCode,
		&i.MaxPlayers,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLobby = `-- name: DeleteLobby :exec
DELETE FROM lobbies WHERE id = $1
`

func (q *Queries) DeleteLobby(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLobby, id)
	return err
}

const deleteUserLobbies = `-- name: DeleteUserLobbies :exec
DELETE FROM lobbies WHERE id IN (
    SELECT lobby_id FROM lobby_players WHERE player_id = $1
)
`

func (q *Queries) DeleteUserLobbies(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserLobbies, playerID)
	return err
}

const findLobbyByCode = `-- name: FindLobbyByCode :one
SELECT id, creator_id, status, invite_code, max_players, created_at FROM lobbies WHERE invite_code = $1 AND status = 'waiting'
`

func (q *Queries) FindLobbyByCode(ctx context.Context, inviteCode string) (Lobby, error) {
	row := q.db.QueryRowContext(ctx, findLobbyByCode, inviteCode)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Status,
		&i.InviteCode,
		&i.MaxPlayers,
		&i.CreatedAt,
	)
	return i, err
}

const getLobby = `-- name: GetLobby :one
SELECT id, creator_id, status, invite_code, max_players, created_at FROM lobbies WHERE id = $1
`

func (q *Queries) GetLobby(ctx context.Context, id uuid.UUID) (Lobby, error) {
	row := q.db.QueryRowContext(ctx, getLobby, id)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Status,
		&i.InviteCode,
		&i.MaxPlayers,
		&i.CreatedAt,
	)
	return i, err
}

const getLobbyPlayers = `-- name: GetLobbyPlayers :many
SELECT player_id FROM lobby_players WHERE lobby_id = $1
`

func (q *Queries) GetLobbyPlayers(ctx context.Context, lobbyID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getLobbyPlayers, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var player_id uuid.UUID
		if err := rows.Scan(&player_id); err != nil {
			return nil, err
		}
		items = append(items, player_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchmakingQueueSize = `-- name: GetMatchmakingQueueSize :one
SELECT COUNT(*) FROM matchmaking_queue
`

func (q *Queries) GetMatchmakingQueueSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMatchmakingQueueSize)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMatchmakingStatus = `-- name: GetMatchmakingStatus :one
SELECT EXISTS(SELECT 1 FROM matchmaking_queue WHERE player_id = $1)
`

func (q *Queries) GetMatchmakingStatus(ctx context.Context, playerID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, getMatchmakingStatus, playerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isPlayerInLobby = `-- name: IsPlayerInLobby :one
SELECT EXISTS(SELECT 1 FROM lobby_players WHERE lobby_id = $1 AND player_id = $2)
`

type IsPlayerInLobbyParams struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) IsPlayerInLobby(ctx context.Context, arg IsPlayerInLobbyParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPlayerInLobby, arg.LobbyID, arg.PlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const joinMatchmaking = `-- name: JoinMatchmaking :exec
INSERT INTO matchmaking_queue (player_id) VALUES ($1)
ON CONFLICT (player_id) DO NOTHING
`

func (q *Queries) JoinMatchmaking(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, joinMatchmaking, playerID)
	return err
}

const leaveMatchmaking = `-- name: LeaveMatchmaking :exec
DELETE FROM matchmaking_queue WHERE player_id = $1
`

func (q *Queries) LeaveMatchmaking(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, leaveMatchmaking, playerID)
	return err
}

const listLobbies = `-- name: ListLobbies :many
SELECT id, creator_id, status, invite_code, max_players, created_at FROM lobbies
WHERE (CASE WHEN $3::text = '' THEN true ELSE status = $3 END)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLobbiesParams struct {
	Limit  int32
	Offset int32
	Status string
}

func (q *Queries) ListLobbies(ctx context.Context, arg ListLobbiesParams) ([]Lobby, error) {
	rows, err := q.db.QueryContext(ctx, listLobbies, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lobby
	for rows.Next() {
		var i Lobby
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Status,
			&i.InviteCode,
			&i.MaxPlayers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLobbyPlayer = `-- name: RemoveLobbyPlayer :exec
DELETE FROM lobby_players WHERE lobby_id = $1 AND player_id = $2
`

type RemoveLobbyPlayerParams struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) RemoveLobbyPlayer(ctx context.Context, arg RemoveLobbyPlayerParams) error {
	_, err := q.db.ExecContext(ctx, removeLobbyPlayer, arg.LobbyID, arg.PlayerID)
	return err
}

const updateLobbyStatus = `-- name: UpdateLobbyStatus :exec
UPDATE lobbies SET status = $2 WHERE id = $1
`

type UpdateLobbyStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateLobbyStatus(ctx context.Context, arg UpdateLobbyStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLobbyStatus, arg.ID, arg.Status)
	return err
}
