// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Lobby struct {
	ID         uuid.UUID
	CreatorID  uuid.UUID
	Status     string
	InviteCode string
	MaxPlayers int32
	CreatedAt  time.Time
}

type LobbyPlayer struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
}

type MatchmakingQueue struct {
	PlayerID uuid.UUID
	JoinedAt time.Time
}

type Profile struct {
	UserID      uuid.UUID
	TotalGames  int32
	Wins        int32
	Losses      int32
	ShipsSunk   int32
	TotalShots  int32
	Hits        int32
	Coins       int32
	Inventory   []string
	ActiveFish  []string
	TotalSpent  int32
	TotalEarned int32
	TimeInBattle int32
}

type User struct {
	ID              uuid.UUID
	Username        string
	PasswordHash    string
	CreatedAt       time.Time
	Email           string
	EmailOtpEnabled bool
	EmailVerified   bool
	TokenVersion    int32
}
