// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Lobby struct {
	ID         uuid.UUID
	CreatorID  uuid.UUID
	Status     string
	InviteCode string
	MaxPlayers int32
	CreatedAt  time.Time
}

type LobbyPlayer struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
}

type MatchmakingQueue struct {
	PlayerID uuid.UUID
	JoinedAt time.Time
}

type Game struct {
	ID          uuid.UUID
	Player1ID   uuid.UUID
	Player2ID   uuid.NullUUID
	Status      string
	CurrentTurn uuid.NullUUID
	WinnerID    uuid.NullUUID
	FinishedAt  sql.NullTime
	CreatedAt   time.Time
}

type GameShip struct {
	ID         uuid.UUID
	GameID     uuid.UUID
	PlayerID   uuid.UUID
	ShipType   int32
	StartX     int32
	StartY     int32
	Horizontal bool
}

type GameMove struct {
	ID        uuid.UUID
	GameID    uuid.UUID
	PlayerID  uuid.UUID
	X         int32
	Y         int32
	Hit       bool
	SunkShipID uuid.NullUUID
}

type Profile struct {
	UserID     uuid.UUID
	TotalGames int32
	Wins       int32
	Losses     int32
	ShipsSunk  int32
	TotalShots int32
	Hits       int32
}

type User struct {
	ID              uuid.UUID
	Username        string
	PasswordHash    string
	CreatedAt       time.Time
	Email           string
	EmailOtpEnabled bool
}
