// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (user_id) VALUES ($1)
`

func (q *Queries) CreateProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createProfile, userID)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, total_games, wins, losses, ships_sunk, total_shots, hits FROM profiles WHERE user_id = $1
`

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.TotalGames,
		&i.Wins,
		&i.Losses,
		&i.ShipsSunk,
		&i.TotalShots,
		&i.Hits,
	)
	return i, err
}
