// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
<<<<<<< HEAD
=======
	"github.com/lib/pq"
>>>>>>> date-+++
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (user_id) VALUES ($1)
`

func (q *Queries) CreateProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createProfile, userID)
	return err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    ROW_NUMBER() OVER (ORDER BY p.wins DESC) AS rank,
    u.id AS player_id,
    u.username,
    p.wins,
    p.losses,
    p.total_games,
    CASE WHEN p.total_games > 0 THEN (p.wins::float8 / p.total_games * 100)::float8 ELSE 0::float8 END AS win_rate,
    CASE WHEN p.total_shots > 0 THEN (p.hits::float8 / p.total_shots * 100)::float8 ELSE 0::float8 END AS hit_rate
FROM profiles p
JOIN users u ON u.id = p.user_id
ORDER BY p.wins DESC
LIMIT $1
`

type GetLeaderboardRow struct {
	Rank       int64
	PlayerID   uuid.UUID
	Username   string
	Wins       int32
	Losses     int32
	TotalGames int32
	WinRate    float64
	HitRate    float64
}

func (q *Queries) GetLeaderboard(ctx context.Context, limit int32) ([]GetLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.Rank,
			&i.PlayerID,
			&i.Username,
			&i.Wins,
			&i.Losses,
			&i.TotalGames,
			&i.WinRate,
			&i.HitRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerRank = `-- name: GetPlayerRank :one
SELECT u.id, u.username, p.wins, p.losses, p.total_games, p.total_shots, p.hits
FROM profiles p
JOIN users u ON u.id = p.user_id
WHERE u.id = $1
`

type GetPlayerRankRow struct {
	ID         uuid.UUID
	Username   string
	Wins       int32
	Losses     int32
	TotalGames int32
	TotalShots int32
	Hits       int32
}

func (q *Queries) GetPlayerRank(ctx context.Context, id uuid.UUID) (GetPlayerRankRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerRank, id)
	var i GetPlayerRankRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Wins,
		&i.Losses,
		&i.TotalGames,
		&i.TotalShots,
		&i.Hits,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
<<<<<<< HEAD
SELECT user_id, total_games, wins, losses, ships_sunk, total_shots, hits FROM profiles WHERE user_id = $1
=======
SELECT user_id, total_games, wins, losses, ships_sunk, total_shots, hits, coins, inventory, active_fish, total_spent, total_earned FROM profiles WHERE user_id = $1
>>>>>>> date-+++
`

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.TotalGames,
		&i.Wins,
		&i.Losses,
		&i.ShipsSunk,
		&i.TotalShots,
		&i.Hits,
<<<<<<< HEAD
=======
		&i.Coins,
		pq.Array(&i.Inventory),
		pq.Array(&i.ActiveFish),
		&i.TotalSpent,
		&i.TotalEarned,
>>>>>>> date-+++
	)
	return i, err
}

const updateProfileStats = `-- name: UpdateProfileStats :exec
UPDATE profiles SET
    total_games = total_games + $2,
    wins = wins + $3,
    losses = losses + $4,
    ships_sunk = ships_sunk + $5,
    total_shots = total_shots + $6,
    hits = hits + $7
WHERE user_id = $1
`

type UpdateProfileStatsParams struct {
	UserID     uuid.UUID
	TotalGames int32
	Wins       int32
	Losses     int32
	ShipsSunk  int32
	TotalShots int32
	Hits       int32
}

func (q *Queries) UpdateProfileStats(ctx context.Context, arg UpdateProfileStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileStats,
		arg.UserID,
		arg.TotalGames,
		arg.Wins,
		arg.Losses,
		arg.ShipsSunk,
		arg.TotalShots,
		arg.Hits,
	)
	return err
}
