// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, email)
VALUES ($1, $2, $3)
RETURNING id, username, email, created_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Email        string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Username  string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash, arg.Email)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const enableEmailOTP = `-- name: EnableEmailOTP :exec
UPDATE users
SET email_otp_enabled = true
WHERE id = $1
`

func (q *Queries) EnableEmailOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, enableEmailOTP, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, email, created_at, email_otp_enabled
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID
	Username        string
	PasswordHash    string
	Email           string
	CreatedAt       time.Time
	EmailOtpEnabled bool
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.EmailOtpEnabled,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, email, created_at, email_otp_enabled
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID              uuid.UUID
	Username        string
	PasswordHash    string
	Email           string
	CreatedAt       time.Time
	EmailOtpEnabled bool
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.EmailOtpEnabled,
	)
	return i, err
}
const updateOTPSecret = `-- name: UpdateOTPSecret :exec
UPDATE users
SET otp_secret = $2
WHERE id = $1
`

type UpdateOTPSecretParams struct {
	ID        uuid.UUID
	OtpSecret sql.NullString
}

func (q *Queries) UpdateOTPSecret(ctx context.Context, arg UpdateOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateOTPSecret, arg.ID, arg.OtpSecret)
	return err
}
