package: api # Имя пакета в сгенерированных Go-файлах
generate:
  models: true # Генерировать структуры данных (например, User, Game)
  embedded-spec: true # Вшить спецификацию внутрь кода (полезно для отладки)
  strict-server: true # ОЧЕНЬ ВАЖНО: включает строгий режим (как у препода)
  chi-server: true # Указывает, что мы будем использовать роутер chi (популярный в Go)
output: internal/api/api.gen.go # Имя файла, в который будет записан код
